### ISSUE TITLE
Creating classes

### ISSUE THREAD

**Issue by ojhermann** [PrincetonUniversity/gerrymandertests#3]
I've been playing with the methods in the `metrics.py` file and have found myself mimicking the functionality in new classes.  For example, I've replaced use of `_stats` in `metrics.py` with a class I call `VoteShares`:

<img width="779" alt="Screen Shot 2020-04-15 at 12 07 15 AM" src="https://user-images.githubusercontent.com/30403309/79282432-15e51c80-7ead-11ea-9186-3c230a3b7797.png">

<img width="909" alt="Screen Shot 2020-04-15 at 12 06 36 AM" src="https://user-images.githubusercontent.com/30403309/79282404-ffd75c00-7eac-11ea-9a6f-c284098df5e5.png">

I had hoped to put up an explanatory PR, but I'm not allowed to make pull requests.  Would you have interest in adding some of these classes to your repo?  They make some use of the methods a bit more concise e.g. 
`mwu: MannWhitneyU = MannWhitneyU([.1, .2, .3, .4, .5, .6, .7, .8, .9, 1.0])`
`mwu.get_statistic()`
`mwu.get_p_value()`

**Comment by hjohns12** [comment]
Thanks for your interest in gerrymetrics! I'm going to change your permissions so that you can submit a PR with these changes.

**Comment by ojhermann** [comment]
Thanks, @hjohns12 

I'll submit the new classes on an individual basis over time; this should make potential debugging easier and allow me to add new classes as they're created.

Would you like me to unit testing for the classes?

**Comment by hjohns12** [comment]
@ojhermann If you have time, that would be great. Thanks.

**Comment by ojhermann** [comment]
Hi @hjohns12 after accepting the invitation it does not appear that I have collaborator access e.g. I'm still receiving permission denied messages when I attempt to to push a branch.  Would you mind adding me as a collaborator again?

**Comment by indraneel** [comment]
@ojhermann can you create a fork and open a PR from there?
